language: php
sudo: false
matrix:
    include:
        - php: hhvm
        - php: 5.6
          env: deps=high
        - php: 5.6
          env: deps=low
        - php: 7.0
          env: deps=low
        - php: 7.0
          env: deps=high
    fast_finish: true

before_install:
    - composer install --no-interaction

script:
    - ./vendor/bin/phpunit --process-isolation

notifications:
    email: "xavier@pandawan-technology.com"
